### ISSUE TITLE
Stop all executions before compile and run

### ISSUE THREAD

**Issue by YuiHrsw** [sam20908/vscode-fastolympiccoding#25]
Maybe a "stop all" button is also necessary?

**Comment by sam20908** [comment]
I'll add a shortcut for it, but I don't think I'll add a button, because I think the default UI should stay the same right now to reach maximum parity with the Sublime Text version (I might allow users to customize the UI, although that'll take much more planning)

**Comment by sam20908** [comment]
Note to self: this also causes process leak

**Comment by sam20908** [comment]
To clarify: if a test case is running and you're re-running it (compile & run all), it will stop the test case and proceed normally. So running one test case does not affect the status of other test cases.

I know this is not *exactly* what you asked for (at least to my interpretation), but due to the design of this extension, enforcing this 100% would effectively mean you can only have one test case running at any given moment, and that currently goes against the strength of being able to interchangeably add/edit/run multiple test cases at once. If the concern is avoiding running any processes against an "older" executable, then the situation can easily be avoided with running all the test cases.
