### ISSUE TITLE
Suggestion: Make the interface design more reasonable

### ISSUE THREAD

**Issue by Kolandaina** [sam20908/vscode-fastolympiccoding#5]
The first point is that when my sidebar is wide enough, the 'run all' and 'delete all' buttons only occupy one line, and at this point, I think it is aesthetically pleasing enough.
![屏幕截图 2024-08-20 152556](https://github.com/user-attachments/assets/c89772e9-0a32-4e3a-a6ef-312d4c3985b6)
But when I reduced the width of the sidebar, these buttons became two lines, which made them less aesthetically pleasing. 
![屏幕截图 2024-08-20 152544](https://github.com/user-attachments/assets/920d25d0-ef06-464e-88d1-713da6737765)
I think you can refer to the design of this plugin in Sublime to make changes.
Second point: In every test case I download, there is a message saying, This is generated from Competitive Companion. Run this testcase to get rid of this message. However, I don't think this prompt is necessary every time. Could you please add an option in the settings to turn it off, or implement another solution?

**Comment by sam20908** [comment]
1) I will look at how they do it 👍 
2) I can add a setting to disable it yes

**Comment by sam20908** [comment]
It turns out that sublime text doesn't handle this well either. I have disabled elements shrinking for now (the text will no longer take 2 lines, and some parts of the row will be cut off), and in the future, I will think of better solutions such as an option to have small icons.

Implemented by https://github.com/sam20908/vscode-fastolympiccoding/commit/5c1c970215c55781454b1aa7df3938b056a06f77, which will come in 1.0.1 sometime tomorrow.
